from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

import numpy as np


BITS_PER_GROUP = 8
DEFAULT_DUMP_FILE = (
    Path(__file__).resolve().parent / "05_repeated_group_train_dump.txt"
)


# ============================================================
# Structured train-dump loading
# ============================================================


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Check repeated-group burst encoding using the self-contained "
            "text dump generated by 05_generate_and_save_trains.py."
        )
    )
    parser.add_argument(
        "dump_path",
        nargs="?",
        type=Path,
        default=DEFAULT_DUMP_FILE,
        help=(
            "Path to the train dump. Default: "
            "05_repeated_group_train_dump.txt next to this script."
        ),
    )
    return parser.parse_args()


def load_train_dump(
    path: Path,
) -> tuple[np.ndarray, np.ndarray, dict[str, str]]:
    """
    Load metadata, X trains, and D trains from one structured text file.
    """
    path = path.expanduser().resolve()

    if not path.is_file():
        raise FileNotFoundError(f"Train dump does not exist: {path}")

    metadata: dict[str, str] = {}
    sections: dict[str, list[int]] = {
        "x_train": [],
        "d_train": [],
    }
    current_section: str | None = None

    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(),
        start=1,
    ):
        line = raw_line.strip()

        if not line or line.startswith("#"):
            continue

        if line in ("[x_train]", "[d_train]"):
            current_section = line[1:-1]
            continue

        if line in ("[/x_train]", "[/d_train]"):
            expected_section = line[2:-1]

            if current_section != expected_section:
                raise ValueError(
                    f"Mismatched section ending at line {line_number}: {line}"
                )

            current_section = None
            continue

        if current_section is not None:
            try:
                sections[current_section].extend(
                    int(value) for value in line.split()
                )
            except ValueError as error:
                raise ValueError(
                    f"Invalid uint32 value at line {line_number}."
                ) from error
            continue

        if "=" not in line:
            raise ValueError(
                f"Invalid metadata line {line_number}: {raw_line}"
            )

        key, value = line.split("=", 1)
        metadata[key.strip()] = value.strip()

    if current_section is not None:
        raise ValueError(f"Unclosed section: [{current_section}]")

    required_metadata = {
        "batch_size",
        "input_count",
        "output_count",
        "bl",
        "words_per_train",
        "out_trans",
        "x_train_length",
        "d_train_length",
    }
    missing_metadata = required_metadata.difference(metadata)

    if missing_metadata:
        missing = ", ".join(sorted(missing_metadata))
        raise KeyError(f"Missing metadata field(s): {missing}")

    x_train = np.asarray(sections["x_train"], dtype=np.uint32)
    d_train = np.asarray(sections["d_train"], dtype=np.uint32)

    stored_x_length = int(metadata["x_train_length"])
    stored_d_length = int(metadata["d_train_length"])

    if len(x_train) != stored_x_length:
        raise ValueError(
            f"Loaded x_train has {len(x_train)} values, "
            f"but metadata says {stored_x_length}."
        )

    if len(d_train) != stored_d_length:
        raise ValueError(
            f"Loaded d_train has {len(d_train)} values, "
            f"but metadata says {stored_d_length}."
        )

    print(f"Loaded train dump: {path}")
    print(f"Loaded X words:    {len(x_train)}")
    print(f"Loaded D words:    {len(d_train)}")

    return x_train, d_train, metadata


def words_from_bl(bl):
    """Number of uint32 words for one sign bit and BL pulse bits."""
    return (bl + 32) // 32


def get_train(
    train,
    feature_idx,
    batch_idx,
    feature_count,
    words_per_train,
    batch_size,
    out_trans,
):
    """Reconstruct one packed train from the flattened backend output."""
    words = []

    for word_idx in range(words_per_train):
        if out_trans:
            batch_aligned = batch_idx + batch_size * feature_idx

            index = (
                (batch_aligned // feature_count)
                * words_per_train
                * feature_count
                + batch_aligned % feature_count
                + word_idx * feature_count
            )
        else:
            index = (
                feature_idx
                + feature_count * word_idx
                + batch_idx * words_per_train * feature_count
            )

        words.append(train[index])

    return np.asarray(words, dtype=np.uint32)


def unpack_train(words, bl):
    """
    Extract the sign and the BL pulse bits.

    Pulse order:
        pulse 0, pulse 1, ..., pulse BL - 1

    The sign bit is excluded from the pulse array.
    """
    sign = int(words[0]) & 1
    pulses = np.empty(bl, dtype=np.uint8)

    for pulse_idx in range(bl):
        if pulse_idx < 31:
            word_idx = 0
            bit_idx = pulse_idx + 1
        else:
            shifted_idx = pulse_idx - 31
            word_idx = 1 + shifted_idx // 32
            bit_idx = shifted_idx % 32

        pulses[pulse_idx] = (
            int(words[word_idx]) >> bit_idx
        ) & 1

    return sign, pulses


def reconstruct_batch(
    train,
    batch_idx,
    feature_count,
    words_per_train,
    batch_size,
    bl,
    out_trans,
):
    """
    Return one batch as:

        signs:  shape (feature_count,)
        pulses: shape (feature_count, BL)

    Rows are ordered by input/output feature index.
    Columns are pulse positions.
    """
    signs = np.empty(feature_count, dtype=np.uint8)
    pulses = np.empty((feature_count, bl), dtype=np.uint8)

    for feature_idx in range(feature_count):
        words = get_train(
            train=train,
            feature_idx=feature_idx,
            batch_idx=batch_idx,
            feature_count=feature_count,
            words_per_train=words_per_train,
            batch_size=batch_size,
            out_trans=out_trans,
        )

        sign, feature_pulses = unpack_train(words, bl)

        signs[feature_idx] = sign
        pulses[feature_idx] = feature_pulses

    return signs, pulses


# ============================================================
# Repeated-group burst reference
# ============================================================


def build_complete_group_sizes(bl):
    """
    Build the complete repeated-group sizes used by the CUDA implementation.

    Examples:
        BL=5   -> (1, 1, 3)
        BL=10  -> (1, 1, 3, 5)
        BL=100 -> (1, 2, 3, 6, 13, 25, 50)
    """
    if bl <= 0:
        raise ValueError("BL must be positive.")

    group_count = int(bl).bit_length()
    total = int(bl)
    large_groups = []

    while group_count > 1:
        preceding_sum = total // 2
        large_groups.append(total - preceding_sum)
        total = preceding_sum
        group_count -= 1

    group_sizes = (total, *reversed(large_groups))

    covered = 0
    for size in group_sizes:
        if size <= 0 or size > covered + 1:
            raise RuntimeError(
                f"Invalid complete group basis for BL={bl}: {group_sizes}"
            )
        covered += size

    if covered != bl:
        raise RuntimeError("Repeated-group sizes do not sum to BL.")

    return group_sizes


def choose_groups_for_count(count, group_sizes):
    """
    Select complete groups, largest first, whose sizes sum to count.

    Returns a binary vector with one entry per group.
    """
    remaining = int(count)
    active_groups = np.zeros(len(group_sizes), dtype=np.uint8)

    for group_idx in range(len(group_sizes) - 1, -1, -1):
        group_size = group_sizes[group_idx]

        if group_size <= remaining:
            active_groups[group_idx] = 1
            remaining -= group_size

    if remaining != 0:
        raise RuntimeError(
            f"Could not represent count={count} with groups={group_sizes}."
        )

    return active_groups


def create_repeated_group_burst_reference(pulses):
    """
    Re-encode every row using contiguous repeated groups.

    For BL=5, the group layout is:
        A B C C C

    A row with population count 4 activates groups B and C:
        0 1 1 1 1
    """
    if pulses.ndim != 2:
        raise ValueError("pulses must be a 2D matrix.")

    bl = pulses.shape[1]
    group_sizes = build_complete_group_sizes(bl)
    group_ids = np.repeat(
        np.arange(len(group_sizes), dtype=np.int64),
        np.asarray(group_sizes, dtype=np.int64),
    )

    reference = np.empty_like(pulses)
    row_counts = pulses.sum(axis=1, dtype=np.int64)

    for feature_idx, pulse_count in enumerate(row_counts):
        active_groups = choose_groups_for_count(
            int(pulse_count),
            group_sizes,
        )
        reference[feature_idx] = active_groups[group_ids]

    return reference, group_sizes, group_ids


# ============================================================
# Burst/permutation analysis
# ============================================================


def get_column_counter(pulses):
    """
    Count complete pulse columns across the IN/OUT dimension.

    Counter preserves duplicate-column multiplicities, which is necessary
    when repeated groups create several identical full-tile masks.
    """
    return Counter(
        tuple(int(bit) for bit in pulses[:, column_idx])
        for column_idx in range(pulses.shape[1])
    )


def analyze_repeated_group_encoding(pulses):
    """
    Classify one complete X or D batch matrix.

    GROUP BURST EXACT:
        Matrix exactly equals the contiguous repeated-group reference.

    GROUP PERMUTED OK:
        Matrix is not in burst order, but its complete columns are exactly a
        common permutation of the burst reference, including multiplicities.

    INVALID:
        Matrix cannot be obtained by a common BL-column permutation of the
        repeated-group burst reference.
    """
    burst_reference, group_sizes, group_ids = (
        create_repeated_group_burst_reference(pulses)
    )

    actual_columns = get_column_counter(pulses)
    reference_columns = get_column_counter(burst_reference)

    matched_columns = sum(
        (actual_columns & reference_columns).values()
    )

    if np.array_equal(pulses, burst_reference):
        status = "GROUP BURST EXACT"
    elif actual_columns == reference_columns:
        status = "GROUP PERMUTED OK"
    else:
        status = "INVALID"

    return (
        status,
        matched_columns,
        burst_reference,
        group_sizes,
        group_ids,
    )


# ============================================================
# Display
# ============================================================


def format_bits(pulses):
    bit_string = "".join(str(int(bit)) for bit in pulses)

    return " ".join(
        bit_string[start:start + BITS_PER_GROUP]
        for start in range(0, len(bit_string), BITS_PER_GROUP)
    )


def format_group_layout(group_ids):
    """Format group IDs as A, B, ..., Z, G26, G27, ..."""
    labels = []

    for group_id in group_ids:
        group_id = int(group_id)
        if group_id < 26:
            labels.append(chr(ord("A") + group_id))
        else:
            labels.append(f"G{group_id}")

    return " ".join(labels)


def print_matrix(name, signs, pulses):
    for feature_idx in range(pulses.shape[0]):
        print(
            f"  {name}{feature_idx:<3} "
            f"s={int(signs[feature_idx])} "
            f"{format_bits(pulses[feature_idx])}"
        )


def inspect_batch_matrix(name, signs, pulses):
    (
        status,
        matched_columns,
        _,
        group_sizes,
        group_ids,
    ) = analyze_repeated_group_encoding(pulses)

    print(
        f"{name}: {status} "
        f"({matched_columns}/{pulses.shape[1]} columns match)"
    )
    print(f"  Group sizes:  {group_sizes}")
    print(f"  Burst layout: {format_group_layout(group_ids)}")

    print_matrix(name, signs, pulses)

    return status



# ============================================================
# Main
# ============================================================


def main() -> None:
    args = parse_arguments()

    x_train, d_train, metadata = load_train_dump(args.dump_path)

    batch_size = int(metadata["batch_size"])
    input_count = int(metadata["input_count"])
    output_count = int(metadata["output_count"])
    bl = int(metadata["bl"])
    stored_words_per_train = int(metadata["words_per_train"])
    out_trans = bool(int(metadata["out_trans"]))

    words_per_train = words_from_bl(bl)

    if words_per_train != stored_words_per_train:
        raise ValueError(
            f"BL={bl} requires {words_per_train} words/train, "
            f"but the dump stores {stored_words_per_train}."
        )

    expected_x_length = input_count * batch_size * words_per_train
    expected_d_length = output_count * batch_size * words_per_train

    if len(x_train) != expected_x_length:
        raise ValueError(
            f"x_train has {len(x_train)} values, "
            f"expected {expected_x_length} from the stored metadata."
        )

    if len(d_train) != expected_d_length:
        raise ValueError(
            f"d_train has {len(d_train)} values, "
            f"expected {expected_d_length} from the stored metadata."
        )

    print("\nStored configuration")
    print(f"  Batch size:       {batch_size}")
    print(f"  Inputs:           {input_count}")
    print(f"  Outputs:          {output_count}")
    print(f"  BL:               {bl}")
    print(f"  Words per train:  {words_per_train}")
    print(f"  out_trans:        {int(out_trans)}")

    if "granularity" in metadata:
        print(f"  Granularity:      {metadata['granularity']}")

    summary = {
        "X": Counter(),
        "D": Counter(),
    }

    print("\nPulse order: pulse 0 -> pulse BL-1")
    print("Signs are displayed separately and excluded from the check.")
    print(
        "A valid permutation must move complete columns identically across "
        "all rows.\n"
    )

    for batch_idx in range(batch_size):
        print(f"--- Batch {batch_idx} ---")

        x_signs, x_pulses = reconstruct_batch(
            train=x_train,
            batch_idx=batch_idx,
            feature_count=input_count,
            words_per_train=words_per_train,
            batch_size=batch_size,
            bl=bl,
            out_trans=out_trans,
        )

        d_signs, d_pulses = reconstruct_batch(
            train=d_train,
            batch_idx=batch_idx,
            feature_count=output_count,
            words_per_train=words_per_train,
            batch_size=batch_size,
            bl=bl,
            out_trans=out_trans,
        )

        x_status = inspect_batch_matrix(
            name="X",
            signs=x_signs,
            pulses=x_pulses,
        )

        d_status = inspect_batch_matrix(
            name="D",
            signs=d_signs,
            pulses=d_pulses,
        )

        summary["X"][x_status] += 1
        summary["D"][d_status] += 1

        print()

    print("Summary")

    for name in ("X", "D"):
        print(
            f"{name}: "
            f"{summary[name]['GROUP BURST EXACT']} exact burst, "
            f"{summary[name]['GROUP PERMUTED OK']} valid permutation, "
            f"{summary[name]['INVALID']} invalid"
        )


if __name__ == "__main__":
    main()